// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class UntitledTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void untitled() {
    driver.Navigate().GoToUrl("https://github.com/AyushGupta74");
    driver.Manage().Window.Size = new System.Drawing.Size(1040, 744);
    driver.FindElement(By.CssSelector("#\\37 33372524 > .repo")).Click();
    driver.FindElement(By.LinkText("Day5")).Click();
    driver.FindElement(By.LinkText("IET_ECommerce")).Click();
    {
      var element = driver.FindElement(By.LinkText("IET_ECommerce"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".avatar")).Click();
    driver.FindElement(By.CssSelector(".user-status-circle-badge > .user-status-emoji-container > div")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".js-calendar-graph > div:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".js-calendar-graph > div:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".js-calendar-graph > div:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.Id("contribution-day-component-6-51")).Click();
    driver.FindElement(By.CssSelector("#user-profile-frame > .position-relative")).Click();
    driver.FindElement(By.CssSelector("#user-profile-frame > .position-relative")).Click();
    driver.FindElement(By.CssSelector("#user-profile-frame > .position-relative")).Click();
    driver.FindElement(By.CssSelector("#user-profile-frame > .position-relative")).Click();
  }
}
